services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888

    networks:
      - internal

  mongo:
    image: mongo:6
    volumes:
      - data:/data/db
    networks:
      - internal
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - internal
      - default
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - 8081:8081

networks:
  internal:

volumes:
  data:
